#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : Routes
Version  : 2.3.1
Release  : 24
URL      : https://pypi.python.org/packages/source/R/Routes/Routes-2.3.1.tar.gz
Source0  : https://pypi.python.org/packages/source/R/Routes/Routes-2.3.1.tar.gz
Summary  : Routing Recognition and Generation Tools
Group    : Development/Tools
License  : MIT
Requires: Routes-python
BuildRequires : WebTest
BuildRequires : beautifulsoup4-python
BuildRequires : coverage-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : repoze.lru-python
BuildRequires : setuptools
BuildRequires : six
BuildRequires : six-python
BuildRequires : waitress-python
BuildRequires : webob-python

%description
routes-logo-haas.svg
Routes logo by Christoph Boehme, 2009.

%package python
Summary: python components for the Routes package.
Group: Default
Provides: routes-python
Requires: repoze.lru-python
Requires: six-python
Requires: webob-python

%description python
python components for the Routes package.


%prep
%setup -q -n Routes-2.3.1

%build
python2 setup.py build -b py2
python3 setup.py build -b py3

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
PYTHONPATH=%{buildroot}/usr/lib/python2.7/site-packages python2 setup.py test
%install
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot}
python3 -tt setup.py build -b py3 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
